services:
  minecraft-cloudflare:
    image: alecblance/minecraft-cloudflare:1.1.1
    container_name: minecraft-cloudflare
    ports:
      - 5000:5000
    environment:
      - NGROK_AUTH_TOKEN=${NGROK_AUTH_TOKEN}
      - MINECRAFT_SERVER_PORT=${MINECRAFT_SERVER_PORT}
      - CLOUDFLARE_API_KEY=${CLOUDFLARE_API_KEY}
      - CLOUDFLARE_ZONE_ID=${CLOUDFLARE_ZONE_ID}
      - CLOUDFLARE_EMAIL=${CLOUDFLARE_EMAIL}
      - SUBDOMAIN_TO_UPDATE=${SUBDOMAIN_TO_UPDATE}
      - MINECRAFT_CLOUDFLARE_SERVER_PORT=${MINECRAFT_CLOUDFLARE_SERVER_PORT}
    restart: unless-stopped
