name: Publish
on:
  workflow_run:
    workflows: [CI]
    branches: [main]
    types: [completed]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker Image
        id: build_image
        if: steps.changesets.outputs.hasChangesets == 'false'
        run: |
          version=${{ fromJson(steps.changesets.outputs.publishedPackages)[0].version }}
          docker build . --file Dockerfile --tag alecblance/minecraft-cloudflare:${version}
      - name: Push Docker Image
        if: steps.build_image.conclusion == 'success'
        run: |
          version=${{ fromJson(steps.changesets.outputs.publishedPackages)[0].version }}
          echo "${{secrets.DOCKER_TOKEN}}" | docker login -u alecblance --password-stdin
          docker push alecblance/minecraft-cloudflare:${version}
